/**
 * Generates lesson content for a range of weeks using an open-source LLM
 * (Groq-hosted openai/gpt-oss-120b) instead of hand-authoring in
 * conversation — see docs/CONTENT_GENERATION.md. Every generated day is
 * validated against the real blueprint/skills data before being written to
 * disk (see validateDay.ts); a day that never passes after retrying is
 * logged as a failure and skipped, never silently shipped with bad content.
 *
 * Usage:
 *   npx tsx scripts/content-gen/generate_days.ts 5        # just week 5
 *   npx tsx scripts/content-gen/generate_days.ts 5-10      # weeks 5 through 10
 */
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import path from 'path';

import { loadDays, loadDesignRules, loadQuestTypes, loadSkills, questTypesForDay, skillForWeek } from './blueprint';
import { callGroqForJson, DailyQuotaExceededError } from './callGroq';
import { buildPrompt, pickFewShotExamples } from './promptBuilder';
import { buildEarliestWeekMap, validateDay } from './validateDay';
import { serializeLessonFile } from './serializeLesson';
import { sanitizeLesson } from './sanitizeLesson';
import { loadAllLessons } from '../lib/loadAllLessons';
import type { DayLesson } from '../../src/lib/curriculum/lesson-types';

const LESSONS_DIR = path.join(__dirname, '..', '..', 'src', 'content', 'lessons', 'everyday-confidence-beginner');
const MAX_ATTEMPTS = 3;

function parseWeekRange(arg: string | undefined): [number, number] {
  if (!arg) return [5, 5];
  const match = arg.match(/^(\d+)(?:-(\d+))?$/);
  if (!match) throw new Error(`Invalid week range: ${arg}`);
  const start = Number(match[1]);
  const end = match[2] ? Number(match[2]) : start;
  return [start, end];
}

function fileNameFor(week: number, day: number): string {
  return `week-${String(week).padStart(2, '0')}-day-${String(day).padStart(2, '0')}.ts`;
}

function exportNameFor(week: number, day: number): string {
  return `week${String(week).padStart(2, '0')}Day${String(day).padStart(2, '0')}`;
}

async function generateOneDay(
  week: number,
  day: number,
  ctx: Awaited<ReturnType<typeof buildContext>>,
): Promise<{ ok: true; warns: string[] } | { ok: false; fails: string[] }> {
  const bp = ctx.daysByWD.get(`${week}-${day}`);
  if (!bp) return { ok: false, fails: [`no blueprint entry for week=${week} day=${day}`] };

  const skill = skillForWeek(ctx.skills, week);
  if (!skill) return { ok: false, fails: [`no skill introduced in week ${week} — is this a review week? not handled yet`] };

  const fewShot = pickFewShotExamples(bp, ctx.allDays, 1, ctx.existingLessons);
  const prompt = buildPrompt({
    day: bp,
    skill,
    questTypes: ctx.questTypes,
    designRules: ctx.designRules,
    fewShotByQuestShape: fewShot,
  });

  let lastFails: string[] = [];
  let lastFailWasApiError = false;
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    // A corrective addendum only makes sense after a real content
    // validation failure — appending it after a Groq API/network error
    // just makes the next prompt bigger for no reason, which is actively
    // counterproductive when the request is already near the token-budget
    // ceiling (see callGroq.ts). Retry with the plain original prompt then.
    const correctivePrompt =
      attempt === 1 || lastFailWasApiError
        ? prompt
        : `${prompt}\n\n## Your previous attempt had these problems — fix them:\n${lastFails.map((f) => `- ${f}`).join('\n')}`;

    let parsed: unknown;
    try {
      parsed = await callGroqForJson(correctivePrompt);
      lastFailWasApiError = false;
    } catch (err) {
      // Daily-quota exhaustion isn't a per-day problem to retry away — the
      // whole run needs to stop, not burn 2 more attempts on this same day
      // (see DailyQuotaExceededError's docs). Propagate it straight out to
      // main(), which stops the batch entirely.
      if (err instanceof DailyQuotaExceededError) throw err;
      lastFails = [`Groq call failed: ${(err as Error).message}`];
      lastFailWasApiError = true;
      continue;
    }

    const sanitized = sanitizeLesson(parsed as Record<string, unknown>);
    const lesson = sanitized as unknown as DayLesson;
    const { fails, warns } = validateDay(lesson, bp, ctx.earliestWeek);
    if (fails.length === 0) {
      const filePath = path.join(LESSONS_DIR, fileNameFor(week, day));
      const header = `// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against\n// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.\n// week=${week}, day=${day}: ${questTypesForDay(bp).join(' + ')}.`;
      const source = serializeLessonFile({ exportName: exportNameFor(week, day), lesson: lesson as unknown as Record<string, unknown>, headerComment: header });
      mkdirSync(LESSONS_DIR, { recursive: true });
      writeFileSync(filePath, source);
      return { ok: true, warns };
    }
    lastFails = fails;
  }
  return { ok: false, fails: lastFails };
}

async function buildContext() {
  const allDays = loadDays();
  return {
    allDays,
    daysByWD: new Map(allDays.map((d) => [`${d.week}-${d.day}`, d])),
    skills: loadSkills(),
    earliestWeek: buildEarliestWeekMap(loadSkills()),
    questTypes: loadQuestTypes(),
    designRules: loadDesignRules(),
    existingLessons: await loadAllLessons(),
  };
}

async function main() {
  const [startWeek, endWeek] = parseWeekRange(process.argv[2]);
  const ctx = await buildContext();

  const results: string[] = [];
  let stoppedForQuota: DailyQuotaExceededError | null = null;
  outer: for (let week = startWeek; week <= endWeek; week++) {
    for (let day = 1; day <= 7; day++) {
      const filePath = path.join(LESSONS_DIR, fileNameFor(week, day));
      if (existsSync(filePath)) {
        console.log(`SKIP week=${week} day=${day}: file already exists`);
        continue;
      }
      process.stdout.write(`week=${week} day=${day}... `);
      try {
        const result = await generateOneDay(week, day, ctx);
        if (result.ok) {
          console.log(`OK${result.warns.length ? ` (${result.warns.length} warning(s): ${result.warns.join('; ')})` : ''}`);
        } else {
          console.log(`FAILED after ${MAX_ATTEMPTS} attempts:\n  ${result.fails.join('\n  ')}`);
          results.push(`week=${week} day=${day}: ${result.fails.join('; ')}`);
        }
      } catch (err) {
        if (err instanceof DailyQuotaExceededError) {
          stoppedForQuota = err;
          break outer;
        }
        throw err;
      }
    }
  }

  if (stoppedForQuota) {
    console.log(
      `\nSTOPPED: Groq's daily token quota for this model is exhausted (needs ~${Math.round(stoppedForQuota.waitSeconds / 60)} min to free up enough for one more day, per its own estimate). Not retrying further in this run — see docs/CONTENT_GENERATION.md. Re-run this same command later once quota has recovered; already-written days are skipped automatically.`,
    );
    process.exitCode = 2;
    return;
  }

  if (results.length > 0) {
    console.log(`\n${results.length} day(s) failed validation and were NOT written:`);
    for (const r of results) console.log(`  - ${r}`);
    process.exitCode = 1;
  } else {
    console.log('\nAll requested days generated and validated successfully.');
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
