import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=5, day=2: learn + speaking.
export const week05Day02: DayLesson = {
  week: 5,
  day: 2,
  skillId: 'describe_family',
  weeklyOutcome: 'Describe family members and relationships.',
  dailyOutcome: 'Describe one family member',
  learnFlow: [
    {
      type: 'intro',
      id: 'intro-1',
      quest: 1,
      emoji: '👪',
      textHi: 'आज हम सीखेंगे कि परिवार के सदस्य को English में कैसे बताएं, विशेषकर have/has और possessives का उपयोग करके। चलिए शुरू करते हैं!',
      textEn: "Today we'll learn how to describe a family member in English using have/has and possessives.",
    },
    {
      type: 'rule',
      id: 'rule-have',
      quest: 1,
      pattern: 'My + [family member] + has + [description].',
      example: 'My mother has brown hair.',
      textHi: 'परिवार के सदस्य का वर्णन करने के लिए यह pattern इस्तेमाल करें।',
    },
    {
      type: 'rule',
      id: 'rule-he-she',
      quest: 1,
      pattern: 'He/She has + [description].',
      example: 'She has two brothers.',
      textHi: "जब आप 'he' या 'she' के साथ बात करते हैं तो यह pattern उपयोग करें।",
    },
    {
      type: 'mcq',
      id: 'mcq-mother',
      quest: 1,
      promptHi: 'निम्न में से कौन सा वाक्य सही है?',
      promptEn: 'Which sentence is correct?',
      options: [
        {
          id: 'a',
          text: 'My mother have brown hair.',
          correct: false,
        },
        {
          id: 'b',
          text: 'My mother has brown hair.',
          correct: true,
        },
        {
          id: 'c',
          text: 'My mother is have brown hair.',
          correct: false,
        },
      ],
      explanationHi: 'सही! "My mother has brown hair." में have की जगह has होना चाहिए।',
      explanationEn: 'Correct! "My mother has brown hair." uses has correctly.',
    },
    {
      type: 'build',
      id: 'build-brother',
      quest: 1,
      promptHi: 'मेरे भाई के पास एक बिल्ली है।',
      answer: [
        'My',
        'brother',
        'has',
        'a',
        'cat.',
      ],
      hint: {
        pattern: 'My + [family member] + has + a + [noun].',
        example: 'My brother has a dog.',
      },
    },
    {
      type: 'mcq',
      id: 'mcq-possessive',
      quest: 1,
      promptHi: 'सही possessive वाक्य चुनें।',
      promptEn: 'Choose the correct possessive sentence.',
      options: [
        {
          id: 'a',
          text: "My father's car is red.",
          correct: true,
        },
        {
          id: 'b',
          text: 'My fathers car is red.',
          correct: false,
        },
        {
          id: 'c',
          text: 'My father car is red.',
          correct: false,
        },
      ],
      explanationHi: 'सही! "father\'s" में apostrophe होना आवश्यक है।',
      explanationEn: 'Correct! "father\'s" needs the apostrophe.',
    },
  ],
  speakFlow: [
    {
      id: 'speak-mother',
      quest: 2,
      promptEn: 'Describe your mother.',
      promptHi: 'अपनी माँ के बारे में बताइए।',
      hint: {
        pattern: 'My mother has + [description].',
        example: 'My mother has brown hair.',
      },
    },
    {
      id: 'speak-father',
      quest: 2,
      promptEn: 'Describe your father.',
      promptHi: 'अपने पिता के बारे में बताइए।',
      hint: {
        pattern: 'My father has + [description].',
        example: 'My father has a beard.',
      },
    },
    {
      id: 'speak-sibling',
      quest: 2,
      promptEn: 'Describe a sibling.',
      promptHi: 'किसी भाई या बहन के बारे में बताइए।',
      hint: {
        pattern: 'My sister has + [description].',
        example: 'My sister has blue eyes.',
      },
    },
    {
      id: 'speak-combine',
      quest: 2,
      promptEn: 'Talk about two family members in one sentence.',
      promptHi: 'एक ही वाक्य में दो परिवार के सदस्यों के बारे में बताइए।',
      hint: {
        pattern: 'My mother has + [description], and my brother has + [description].',
        example: 'My mother has brown hair, and my brother has a bike.',
      },
    },
    {
      id: 'speak-final',
      quest: 2,
      promptEn: 'Last one — introduce a family member and say something they have.',
      promptHi: 'आखिरी सवाल — एक परिवार के सदस्य का परिचय दें और बताइए उनके पास क्या है।',
      isFinal: true,
    },
  ],
};
