import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=6, day=5: translation + speaking.
export const week06Day05: DayLesson = {
  week: 6,
  day: 5,
  skillId: 'describe_home',
  weeklyOutcome: 'Describe your home and where things are.',
  dailyOutcome: 'Describe what you like about your home',
  learnFlow: [
    {
      type: 'intro',
      id: 'intro-home-1',
      quest: 1,
      emoji: '🏠',
      textHi: 'आज हम अपने घर के बारे में बात करेंगे।',
      textEn: 'Today we will talk about your home.',
    },
    {
      type: 'rule',
      id: 'rule-exist-1',
      quest: 1,
      pattern: 'There is/are + [noun] + [preposition] + [location].',
      example: 'There is a sofa in the living room.',
      textHi: "घर में चीज़ें बताने के लिए 'there is' या 'there are' का प्रयोग करें।",
    },
    {
      type: 'build',
      id: 'translate-window-1',
      quest: 1,
      promptHi: 'मेरे कमरे में एक बड़ी खिड़की है।',
      answer: [
        'There',
        'is',
        'a',
        'big',
        'window',
        'in',
        'my',
        'room.',
      ],
      hint: {
        pattern: 'There is + [noun] + [preposition] + [location].',
        example: 'There is a lamp on the table.',
      },
    },
    {
      type: 'build',
      id: 'translate-fridge-2',
      quest: 1,
      promptHi: 'रसोई में एक फ्रिज है।',
      answer: [
        'There',
        'is',
        'a',
        'fridge',
        'in',
        'the',
        'kitchen.',
      ],
      hint: {
        pattern: 'There is + [noun] + [preposition] + [location].',
        example: 'There is a fridge in the kitchen.',
      },
    },
    {
      type: 'build',
      id: 'translate-wardrobe-3',
      quest: 1,
      promptHi: 'बैडरूम में बिस्तर के नीचे एक अलमारी है।',
      answer: [
        'There',
        'is',
        'a',
        'wardrobe',
        'under',
        'the',
        'bed',
        'in',
        'the',
        'bedroom.',
      ],
      hint: {
        pattern: 'There is + [noun] + [preposition] + [reference].',
        example: 'There is a cat under the table.',
      },
    },
  ],
  speakFlow: [
    {
      id: 'speak-like-1',
      quest: 2,
      promptEn: 'Say one thing you like about your home.',
      promptHi: 'बताइए आपके घर में आपको क्या पसंद है।',
      hint: {
        pattern: 'I like + [noun] + [preposition] + [location].',
        example: 'I like the garden behind my house.',
      },
    },
    {
      id: 'speak-like-2',
      quest: 2,
      promptEn: 'Add another thing you like, using a different room.',
      promptHi: 'एक और चीज़ बताइए जो आपको अपने घर के किसी अलग कमरे में पसंद है।',
    },
    {
      id: 'speak-dislike',
      quest: 2,
      promptEn: "Say one thing you don't like about your home.",
      promptHi: 'बताइए आपके घर में आपको क्या नापसंद है।',
      hint: {
        pattern: "I don't like + [noun] + [preposition] + [location].",
        example: "I don't like the noise in the hallway.",
      },
    },
    {
      id: 'speak-combo',
      quest: 2,
      promptEn: "Combine what you like and don't like into one or two sentences.",
      promptHi: 'पसंद और नापसंद को एक या दो sentences में मिलाकर बोलिए।',
    },
    {
      id: 'speak-final',
      quest: 2,
      promptEn: 'Now talk naturally about your home, as if telling a friend.',
      promptHi: 'अब अपने दोस्त को अपने घर के बारे में प्राकृतिक तरीके से बताइए।',
      isFinal: true,
    },
  ],
};
