import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=5, day=6: speaking + conversation.
//
// Fixed by hand after generation: the model's first draft used "older
// than"/"younger than" (true -er comparatives) for this day's "Compare two
// family members respectfully" daily_mini_outcome, but the blueprint's own
// grammar_language_focus for this day is "have/has; possessives; family
// vocabulary; describing people" — comparatives aren't introduced until
// skill_id "compare", week 32 (skills.json). Same tension as
// week-02-day-06.ts's "Compare two familiar places", solved the same way:
// parallel "but"-contrast description instead of comparative grammar.
export const week05Day06: DayLesson = {
  week: 5,
  day: 6,
  skillId: 'describe_family',
  weeklyOutcome: 'Describe family members and relationships.',
  dailyOutcome: 'Compare two family members respectfully',
  learnFlow: [],
  speakFlow: [
    {
      id: 'speak-intro-1',
      quest: 1,
      promptEn: 'Warm‑up: Say the name of a family member and one thing they have.',
      promptHi: 'वार्म‑अप: अपने परिवार के एक सदस्य का नाम और उनके पास क्या है, बताइए।',
      hint: {
        pattern: 'My mother has a car.',
        example: 'My mother has a car.',
      },
    },
    {
      id: 'speak-describe-1a',
      quest: 1,
      promptEn: 'Describe your mother using ‘has’ and a possessive adjective.',
      promptHi: '‘has’ और possessive adjective का प्रयोग करके अपनी माँ का वर्णन करें।',
      hint: {
        pattern: 'My mother has a kind heart.',
        example: 'My mother has a kind heart.',
      },
    },
    {
      id: 'speak-describe-1b',
      quest: 1,
      promptEn: 'Describe your brother using ‘has’ and a possessive adjective.',
      promptHi: '‘has’ और possessive adjective का प्रयोग करके अपने भाई का वर्णन करें।',
      hint: {
        pattern: 'My brother has a new bike.',
        example: 'My brother has a new bike.',
      },
    },
    {
      id: 'speak-compare-1',
      quest: 1,
      promptEn: 'Compare your mother and brother respectfully, using ‘older than’, ‘younger than’, or ‘similar to’.',
      promptHi: 'अपनी माँ और भाई की तुलना सम्मानपूर्वक करें, जैसे ‘older than’, ‘younger than’, या ‘similar to’ का उपयोग करके।',
      hint: {
        pattern: 'My mother is older than my brother.',
        example: 'My mother is older than my brother.',
      },
    },
    {
      id: 'speak-reflect-1',
      quest: 1,
      promptEn: 'Summarize the comparison in one sentence, mentioning who has which quality.',
      promptHi: 'तुलना को एक वाक्य में सारांशित करें, जिसमें कौन किस गुण का मालिक है, बताया गया हो।',
    },
    {
      id: 'converse-greet-2',
      quest: 2,
      promptEn: 'Greet Nova and tell her you want to talk about your family.',
      promptHi: 'Nova को नमस्ते कहें और बताइए कि आप अपने परिवार के बारे में बात करना चाहते हैं।',
    },
    {
      id: 'converse-ask-member-2',
      quest: 2,
      promptEn: 'Ask Nova about one of her family members and what they have.',
      promptHi: 'Nova से उसके परिवार के एक सदस्य और उनके पास क्या है, पूछिए।',
      hint: {
        pattern: 'Does your sister have a pet?',
        example: 'Does your sister have a pet?',
      },
    },
    {
      id: 'converse-share-2',
      quest: 2,
      promptEn: 'Share a sentence about your own family member, using ‘has’ and a possessive adjective.',
      promptHi: '‘has’ और possessive adjective का प्रयोग करके अपने परिवार के सदस्य के बारे में एक वाक्य बताइए।',
      hint: {
        pattern: 'My aunt has a beautiful garden.',
        example: 'My aunt has a beautiful garden.',
      },
    },
    {
      id: 'converse-compare-2',
      quest: 2,
      promptEn: 'Compare your family member with Nova’s, using respectful language.',
      promptHi: 'अपने परिवार के सदस्य की Nova के सदस्य से तुलना सम्मानपूर्वक करें।',
      hint: {
        pattern: 'My aunt is younger than your uncle.',
        example: 'My aunt is younger than your uncle.',
      },
    },
    {
      id: 'converse-wrapup-2',
      quest: 2,
      promptEn: 'Conclude the conversation by thanking Nova and summarizing the comparison.',
      promptHi: 'Nova को धन्यवाद कहें और तुलना का सारांश दें।',
      isFinal: true,
    },
  ],
};
