import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=7, day=4: conversation.
export const week07Day04: DayLesson = {
  week: 7,
  day: 4,
  skillId: 'describe_friend',
  weeklyOutcome: 'Talk about friends and what you do together.',
  dailyOutcome: 'Ask a friend about their plans',
  learnFlow: [],
  speakFlow: [
    {
      id: 'converse-greet',
      quest: 1,
      promptEn: 'Greet your friend and ask how they are.',
      promptHi: 'अपने दोस्त को नमस्ते कहिए और पूछिए कि वह कैसे हैं?',
      hint: {
        pattern: 'Hi/Hello + [name]! How are you?',
        example: 'Hi Rohan! How are you?',
      },
    },
    {
      id: 'converse-ask-plans',
      quest: 1,
      promptEn: 'Ask your friend what they are planning to do today.',
      promptHi: 'आप आज क्या करने की योजना बना रहे हैं, पूछिए।',
      hint: {
        pattern: 'What are you doing today?',
        example: 'What are you doing today?',
      },
    },
    {
      id: 'converse-share-plans',
      quest: 1,
      promptEn: "Share your own plan and use 'but' to contrast.",
      promptHi: 'आप अपनी योजना बताइए, लेकिन एक विरोधी बात जोड़िए।',
      hint: {
        pattern: 'I am going to ... but I also ...',
        example: 'I am going to the library, but I also want to meet a friend.',
      },
    },
    {
      id: 'converse-suggest-activity',
      quest: 1,
      promptEn: "Suggest doing an activity together using 'and'.",
      promptHi: "एक साथ कुछ करने का सुझाव दीजिए, जिसमें 'and' का प्रयोग हो।",
      hint: {
        pattern: 'Would you like to ... and ...?',
        example: 'Would you like to watch a movie and have coffee?',
      },
    },
    {
      id: 'converse-wrap',
      quest: 1,
      promptEn: 'Have a short back-and-forth confirming your plans.',
      promptHi: 'एक छोटी बातचीत कीजिए जहाँ आप दोनों अपनी योजनाओं की पुष्टि करें।',
      isFinal: true,
    },
  ],
};
