import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=5, day=3: listening + speaking.
export const week05Day03: DayLesson = {
  week: 5,
  day: 3,
  skillId: 'describe_family',
  weeklyOutcome: 'Describe family members and relationships.',
  dailyOutcome: 'Say what family members do',
  learnFlow: [
    {
      type: 'intro',
      id: 'listen-1',
      quest: 1,
      emoji: '🎧',
      textHi: 'ध्यान से सुनिए, फिर बताइए कौन‑कौन से परिवार के सदस्य काम कर रहे हैं।',
      textEn: 'Listen carefully, then tell which family members are doing something.',
      audioTextEn: 'My mother cooks dinner, and my brother plays cricket.',
    },
    {
      type: 'mcq',
      id: 'listen-identify',
      quest: 1,
      promptHi: 'निम्नलिखित में से कौन‑सा वाक्य सुना गया?',
      promptEn: 'Which sentence was heard?',
      options: [
        {
          id: 'a',
          text: 'My mother cooks dinner, and my brother plays cricket.',
          correct: true,
        },
        {
          id: 'b',
          text: 'My mother reads a book, and my brother watches TV.',
          correct: false,
        },
        {
          id: 'c',
          text: 'My father cooks dinner, and my sister plays cricket.',
          correct: false,
        },
      ],
      explanationHi: 'सही! यही वाक्य आपने सुना।',
      explanationEn: 'Correct! That’s the sentence you heard.',
      audioTextEn: 'My mother cooks dinner, and my brother plays cricket.',
    },
    {
      type: 'mcq',
      id: 'listen-meaning',
      quest: 1,
      promptHi: '‘cooks dinner’ का क्या मतलब है?',
      promptEn: 'What does “cooks dinner” mean?',
      options: [
        {
          id: 'a',
          text: 'रात का भोजन तैयार करता है।',
          correct: true,
        },
        {
          id: 'b',
          text: 'खाना खाता है।',
          correct: false,
        },
        {
          id: 'c',
          text: 'भोजन साफ करता है।',
          correct: false,
        },
      ],
      explanationHi: '‘cooks dinner’ का अर्थ है रात का भोजन तैयार करना।',
      explanationEn: '‘cooks dinner’ means prepares the evening meal.',
      audioTextEn: 'My mother cooks dinner, and my brother plays cricket.',
    },
    {
      type: 'mcq',
      id: 'listen-response',
      quest: 1,
      promptHi: 'यदि आप बताना चाहते हैं कि आपकी बहन क्या करती है, तो सही उत्तर कौन‑सा होगा?',
      promptEn: 'If you want to say what your sister does, which response is correct?',
      options: [
        {
          id: 'a',
          text: 'My sister cleans the house.',
          correct: true,
        },
        {
          id: 'b',
          text: 'My sister cooks dinner.',
          correct: false,
        },
        {
          id: 'c',
          text: 'My sister plays cricket.',
          correct: false,
        },
      ],
      explanationHi: 'सही! यह वही क्रिया है जो आप बताना चाहते हैं।',
      explanationEn: 'Correct! That’s the action you want to describe.',
      audioTextEn: 'My sister cleans the house.',
    },
    {
      type: 'build',
      id: 'listen-retell',
      quest: 1,
      promptHi: 'सुनी हुई sentence को फिर से लिखिए।',
      answer: [
        'My',
        'mother',
        'cooks',
        'dinner,',
        'and',
        'my',
        'brother',
        'plays',
        'cricket.',
      ],
      hint: {
        pattern: '[Subject] + cooks + dinner, + and + [Subject] + plays + cricket.',
        example: 'My mother cooks dinner, and my brother plays cricket.',
      },
      audioTextEn: 'My mother cooks dinner, and my brother plays cricket.',
    },
  ],
  speakFlow: [
    {
      id: 'speak-family-1',
      quest: 2,
      promptEn: 'Say who in your family cooks dinner.',
      promptHi: 'बताइए आपके परिवार में कौन खाना बनाता है।',
      hint: {
        pattern: '[Family member] + cooks dinner.',
        example: 'My mother cooks dinner.',
      },
    },
    {
      id: 'speak-family-2',
      quest: 2,
      promptEn: 'Say who in your family plays cricket.',
      promptHi: 'बताइए आपके परिवार में कौन क्रिकेट खेलता है।',
      hint: {
        pattern: '[Family member] + plays cricket.',
        example: 'My brother plays cricket.',
      },
    },
    {
      id: 'speak-family-3',
      quest: 2,
      promptEn: 'Combine the two sentences into a short paragraph about your family activities.',
      promptHi: 'अपने परिवार की दो गतिविधियों को एक साथ जोड़कर दो‑तीन sentences में बताइए।',
      hint: {
        pattern: 'My mother ... and my brother ...',
        example: 'My mother cooks dinner, and my brother plays cricket.',
      },
    },
    {
      id: 'speak-family-4',
      quest: 2,
      promptEn: 'Talk about another family member and what they do, using ‘has’ or ‘have’ to describe possession.',
      promptHi: 'एक और परिवार के सदस्य के बारे में बताइए और वह क्या करता/करती है, साथ में ‘has’ या ‘have’ का प्रयोग करें।',
      hint: {
        pattern: 'My sister has a cat.',
        example: 'My sister has a cat.',
      },
    },
    {
      id: 'speak-final',
      quest: 2,
      promptEn: 'Talk naturally about what different family members do, as if speaking to a friend.',
      promptHi: 'दोस्त को बताइए आपके परिवार के सदस्य क्या क्या करते हैं, प्राकृतिक रूप से।',
      isFinal: true,
    },
  ],
};
