import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=5, day=5: translation + speaking.
export const week05Day05: DayLesson = {
  week: 5,
  day: 5,
  skillId: 'describe_family',
  weeklyOutcome: 'Describe family members and relationships.',
  dailyOutcome: 'Talk about family activities',
  learnFlow: [
    {
      type: 'build',
      id: 'translate-family-1',
      quest: 1,
      promptHi: 'मेरी माँ के पास एक beautiful garden है।',
      answer: [
        'My',
        'mother',
        'has',
        'a',
        'beautiful',
        'garden.',
      ],
      hint: {
        pattern: '[Subject] has + [object].',
        example: 'My mother has a beautiful garden.',
      },
    },
    {
      type: 'build',
      id: 'translate-family-2',
      quest: 1,
      promptHi: 'मेरे पिता के पास एक toolbox है।',
      answer: [
        'My',
        'father',
        'has',
        'a',
        'toolbox.',
      ],
      hint: {
        pattern: '[Subject] has + [object].',
        example: 'My father has a toolbox.',
      },
    },
    {
      type: 'build',
      id: 'translate-family-3',
      quest: 1,
      promptHi: 'मेरी बहन को painting पसंद है।',
      answer: [
        'My',
        'sister',
        'likes',
        'painting.',
      ],
      hint: {
        pattern: '[Subject] likes + [activity].',
        example: 'My sister likes painting.',
      },
    },
    {
      type: 'build',
      id: 'translate-family-4',
      quest: 1,
      promptHi: 'हम हर रविवार को together dinner करते हैं।',
      answer: [
        'We',
        'have',
        'dinner',
        'together',
        'every',
        'Sunday.',
      ],
      hint: {
        pattern: 'We have + [activity] + [time].',
        example: 'We have dinner together every Sunday.',
      },
    },
    {
      type: 'build',
      id: 'translate-family-5',
      quest: 1,
      promptHi: 'मेरे भाई के पास एक new bike है, और वह उसे रोज़ ride करता है।',
      answer: [
        'My',
        'brother',
        'has',
        'a',
        'new',
        'bike',
        'and',
        'he',
        'rides',
        'it',
        'every',
        'day.',
      ],
      hint: {
        pattern: '[Subject] has + [object] + and + [pronoun] + [verb] + it + [frequency].',
        example: 'My brother has a new bike and he rides it every day.',
      },
    },
  ],
  speakFlow: [
    {
      id: 'speak-activity-1',
      quest: 2,
      promptEn: 'Tell me one activity your mother likes to do.',
      promptHi: 'बताइए आपकी माँ को कौन‑सी activity पसंद है।',
      hint: {
        pattern: 'My mother likes + [activity].',
        example: 'My mother likes cooking.',
      },
    },
    {
      id: 'speak-activity-2',
      quest: 2,
      promptEn: 'Tell me something your father has that he uses regularly.',
      promptHi: 'बताइए आपके पिता के पास क्या है जो वह नियमित रूप से उपयोग करते हैं।',
      hint: {
        pattern: 'My father has a + [object] that he uses daily.',
        example: 'My father has a watch that he uses daily.',
      },
    },
    {
      id: 'speak-activity-3',
      quest: 2,
      promptEn: 'Describe a hobby your sister enjoys.',
      promptHi: 'बताइए आपकी बहन कौन‑सा hobby enjoy करती है।',
      hint: {
        pattern: 'My sister enjoys + [hobby].',
        example: 'My sister enjoys reading.',
      },
    },
    {
      id: 'speak-activity-4',
      quest: 2,
      promptEn: 'Talk about a weekly family activity you all do together.',
      promptHi: 'बताइए आपका परिवार हर हफ्ते कौन‑सी activity एक साथ करता है।',
      hint: {
        pattern: 'We have + [activity] together every week.',
        example: 'We have movie night together every week.',
      },
    },
    {
      id: 'speak-final',
      quest: 2,
      promptEn: "Now, share a short story about a recent family activity, using 'have/has' and possessives.",
      promptHi: "अब एक हालिया परिवार की activity के बारे में छोटी कहानी बताइए, जिसमें 'have/has' और possessives का उपयोग हो।",
      isFinal: true,
    },
  ],
};
