import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=6, day=4: listening + conversation.
export const week06Day04: DayLesson = {
  week: 6,
  day: 4,
  skillId: 'describe_home',
  weeklyOutcome: 'Describe your home and where things are.',
  dailyOutcome: 'Ask where something is',
  learnFlow: [
    {
      type: 'intro',
      id: 'listen-1',
      quest: 1,
      emoji: '🎧',
      textHi: 'ध्यान से सुनिए। यह वाक्य सुनिए।',
      textEn: 'Listen carefully to the sentence.',
      audioTextEn: 'Where is the book?',
    },
    {
      type: 'mcq',
      id: 'listen-identify',
      quest: 1,
      promptHi: 'Nova ने क्या कहा?',
      promptEn: 'What did Nova say?',
      options: [
        {
          id: 'a',
          text: 'Where is the book?',
          correct: true,
        },
        {
          id: 'b',
          text: 'Where are the book?',
          correct: false,
        },
        {
          id: 'c',
          text: 'What is the book?',
          correct: false,
        },
      ],
      explanationHi: 'सही! शब्द पहचानना ज़रूरी है।',
      explanationEn: 'Correct! Spotting the exact words matters.',
      audioTextEn: 'Where is the book?',
    },
    {
      type: 'mcq',
      id: 'listen-meaning',
      quest: 1,
      promptHi: 'इस सवाल का मतलब क्या है?',
      promptEn: 'What does this question mean?',
      options: [
        {
          id: 'a',
          text: 'किताब कहाँ है?',
          correct: true,
        },
        {
          id: 'b',
          text: 'किताब क्या है?',
          correct: false,
        },
        {
          id: 'c',
          text: 'किताब कौन पढ़ रहा है?',
          correct: false,
        },
      ],
      explanationHi: 'सही! यह पूछ रहा है कि किताब कहाँ है।',
      explanationEn: 'Correct! It asks where the book is.',
      audioTextEn: 'Where is the book?',
    },
    {
      type: 'mcq',
      id: 'listen-response',
      quest: 1,
      isPopQuiz: true,
      promptHi: 'सही जवाब कौन सा है?',
      promptEn: 'What would be an appropriate response?',
      options: [
        {
          id: 'a',
          text: 'The book is on the table.',
          correct: true,
        },
        {
          id: 'b',
          text: 'I have a book.',
          correct: false,
        },
        {
          id: 'c',
          text: 'The book is red.',
          correct: false,
        },
      ],
      hint: {
        pattern: 'The book is + preposition + the + location.',
        example: 'The book is on the table.',
      },
      explanationHi: 'सही! जवाब में स्थान बताना चाहिए।',
      explanationEn: 'Correct! The reply should state the location.',
      audioTextEn: 'Where is the book?',
    },
    {
      type: 'build',
      id: 'listen-retell',
      quest: 1,
      promptHi: 'जो sentence आपने अभी सुना, उसे फिर से बनाइए।',
      answer: [
        'The',
        'book',
        'is',
        'on',
        'the',
        'shelf.',
      ],
      hint: {
        pattern: 'The + noun + is + preposition + the + location.',
        example: 'The pen is in the drawer.',
      },
      audioTextEn: 'The book is on the shelf.',
    },
  ],
  speakFlow: [
    {
      id: 'converse-ask-location',
      quest: 2,
      promptEn: 'Ask Nova where the kitchen is.',
      promptHi: 'Nova से पूछिए रसोईघर कहाँ है।',
      hint: {
        pattern: 'Where is the kitchen?',
        example: 'Where is the kitchen?',
      },
    },
    {
      id: 'converse-ask-bathroom',
      quest: 2,
      promptEn: 'Ask Nova where the bathroom is.',
      promptHi: 'Nova से पूछिए बाथरूम कहाँ है।',
      hint: {
        pattern: 'Where is the bathroom?',
        example: 'Where is the bathroom?',
      },
    },
    {
      id: 'converse-respond',
      quest: 2,
      promptEn: 'Nova पूछती है सोफ़ा कहाँ है — जवाब दीजिए।',
      promptHi: 'Nova पूछती है सोफ़ा कहाँ है — उत्तर दीजिए।',
      hint: {
        pattern: 'The sofa is + preposition + the + location.',
        example: 'The sofa is next to the TV.',
      },
    },
    {
      id: 'converse-followup',
      quest: 2,
      promptEn: 'Nova पूछती है क्या वह खिड़की के नीचे है — उत्तर दीजिए।',
      promptHi: 'Nova पूछती है क्या वह खिड़की के नीचे है — उत्तर दीजिए।',
      hint: {
        pattern: 'Yes, it is.',
        example: 'Yes, it is.',
      },
    },
    {
      id: 'converse-full',
      quest: 2,
      promptEn: "Have a short dialogue: ask where two items are and answer Nova's questions.",
      promptHi: 'एक छोटी बातचीत कीजिए: दो वस्तुओं के स्थान पूछिए और Nova के प्रश्नों का उत्तर दीजिए।',
      isFinal: true,
    },
  ],
};
