import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=6, day=6: review + speaking.
export const week06Day06: DayLesson = {
  week: 6,
  day: 6,
  skillId: 'describe_home',
  weeklyOutcome: 'Describe your home and where things are.',
  dailyOutcome: 'Give a simple tour of your home',
  learnFlow: [
    {
      type: 'intro',
      id: 'intro-1',
      quest: 1,
      emoji: '🏡',
      textHi: 'आज हम घर के बारे में पहले सीखा हुआ दोहराएँगे और नई बातों को जोड़ेंगे।',
      textEn: 'Today we will review what we learned about the house and add new details.',
    },
    {
      type: 'rule',
      id: 'rule-there',
      quest: 1,
      pattern: 'There is/are + [object] + [preposition] + [room].',
      example: 'There is a sofa in the living room.',
      textHi: 'घर में वस्तु बताने के लिए यह pattern इस्तेमाल करें।',
    },
    {
      type: 'mcq',
      id: 'mcq-singular',
      quest: 1,
      promptHi: 'निम्न में से कौन सा sentence सही है?',
      promptEn: 'Which sentence is correct?',
      options: [
        {
          id: 'a',
          text: 'There are a table in the kitchen.',
          correct: false,
        },
        {
          id: 'b',
          text: 'There is a table in the kitchen.',
          correct: true,
        },
        {
          id: 'c',
          text: 'There is a tables in the kitchen.',
          correct: false,
        },
      ],
      explanationHi: 'सही! "There is" एकवचन वस्तु के लिए प्रयोग होता है।',
      explanationEn: 'Correct! "There is" is used for a singular object.',
    },
    {
      type: 'build',
      id: 'build-toilet',
      quest: 1,
      promptHi: 'मेरे बाथरूम में एक टॉयलेट है।',
      answer: [
        'There',
        'is',
        'a',
        'toilet',
        'in',
        'the',
        'bathroom.',
      ],
      hint: {
        pattern: 'There is + [object] + in + [room].',
        example: 'There is a sink in the bathroom.',
      },
    },
    {
      type: 'mcq',
      id: 'mcq-prep',
      quest: 1,
      promptHi: 'वाक्य पूरा करें: There is a lamp ___ the bedroom.',
      promptEn: 'Complete the sentence: There is a lamp ___ the bedroom.',
      options: [
        {
          id: 'a',
          text: 'under',
          correct: false,
        },
        {
          id: 'b',
          text: 'on',
          correct: false,
        },
        {
          id: 'c',
          text: 'in',
          correct: true,
        },
      ],
      explanationHi: 'कमरे के अंदर के लिए "in" प्रयोग करें।',
      explanationEn: 'Use "in" for inside a room.',
    },
  ],
  speakFlow: [
    {
      id: 'speak-start',
      quest: 2,
      promptEn: 'Start by saying what room you are in now.',
      promptHi: 'अब बताइए आप अभी किस कमरे में हैं।',
      hint: {
        pattern: 'I am in the + [room].',
        example: 'I am in the living room.',
      },
    },
    {
      id: 'speak-object',
      quest: 2,
      promptEn: 'Describe one object in that room using there is/are.',
      promptHi: 'उस कमरे में एक वस्तु बताइए।',
      hint: {
        pattern: 'There is/are + [object] + in the + [room].',
        example: 'There is a sofa in the living room.',
      },
    },
    {
      id: 'speak-prep',
      quest: 2,
      promptEn: 'Now move to another room and describe where an object is located using a preposition (on, under, next to).',
      promptHi: 'अब किसी दूसरे कमरे में जाएँ और एक वस्तु का स्थान बताइए, जैसे on, under, next to।',
      hint: {
        pattern: 'There is a + [object] + [preposition] + the + [furniture] + in the + [room].',
        example: 'There is a book on the table in the study.',
      },
    },
    {
      id: 'speak-tour',
      quest: 2,
      promptEn: 'Give a short two‑sentence tour combining the rooms you have mentioned.',
      promptHi: 'अब दो वाक्यों में अपने घर का छोटा tour बताइए।',
      hint: {
        pattern: 'I am in the + [room]. There is a + [object] + in the + [room].',
        example: 'I am in the kitchen. There is a fridge in the kitchen.',
      },
    },
    {
      id: 'speak-final',
      quest: 2,
      promptEn: 'Give a quick tour of your whole home, mentioning at least three rooms and objects, as if you are showing it to a friend.',
      promptHi: 'एक दोस्त को दिखाते हुए अपने घर का तेज़ tour दें, कम से कम तीन कमरे और वस्तुएँ बताइए।',
      isFinal: true,
    },
  ],
};
