import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=7, day=2: learn + speaking.
export const week07Day02: DayLesson = {
  week: 7,
  day: 2,
  skillId: 'describe_friend',
  weeklyOutcome: 'Talk about friends and what you do together.',
  dailyOutcome: 'Describe what you do together',
  learnFlow: [
    {
      type: 'intro',
      id: 'intro-1',
      quest: 1,
      emoji: '👥',
      textHi: 'आज हम सीखेंगे कि आप अपने दोस्त के साथ क्या करते हैं — यह English में कैसे कहें। चलिए शुरू करते हैं!',
      textEn: "Today we'll learn how to talk about what you do with a friend in English. Let's begin!",
    },
    {
      type: 'rule',
      id: 'rule-present',
      quest: 1,
      pattern: 'Subject + verb (present simple) + activity.',
      example: 'I play cricket with my friend.',
      textHi: 'आप या आपका दोस्त जो activity करते हैं, उसे present simple में बताने के लिए यह pattern इस्तेमाल करें।',
    },
    {
      type: 'rule',
      id: 'rule-andbut',
      quest: 1,
      pattern: 'Subject + verb + activity + and/but + another activity.',
      example: 'We study together, and we watch movies.',
      textHi: "दो activities को जोड़ने के लिए 'and' या 'but' का उपयोग करें।",
    },
    {
      type: 'mcq',
      id: 'mcq-present',
      quest: 1,
      promptHi: 'कौन सा वाक्य सही ढंग से present simple में बताता है कि आप अपने दोस्त के साथ क्या करते हैं?',
      promptEn: 'Which sentence correctly uses present simple to say what you do with a friend?',
      options: [
        {
          id: 'a',
          text: 'I am playing cricket with my friend yesterday.',
          correct: false,
        },
        {
          id: 'b',
          text: 'We play cricket with my friend.',
          correct: true,
        },
        {
          id: 'c',
          text: 'We played cricket with my friend.',
          correct: false,
        },
      ],
      explanationHi: 'सही! "We play cricket with my friend." present simple में है।',
      explanationEn: 'Correct! "We play cricket with my friend." is in present simple.',
    },
    {
      type: 'mcq',
      id: 'mcq-andbut',
      quest: 1,
      promptHi: "दो activities को जोड़ने के लिए 'and' या 'but' का सही उपयोग कौन सा है?",
      promptEn: "Which sentence correctly uses 'and' or 'but' to connect two activities?",
      options: [
        {
          id: 'a',
          text: 'We study together, and we watch movies.',
          correct: true,
        },
        {
          id: 'b',
          text: 'We study together or we watch movies.',
          correct: false,
        },
        {
          id: 'c',
          text: 'We study together, but we watch movies, and we also eat snacks.',
          correct: false,
        },
      ],
      explanationHi: 'सही! "and" दो समान activities को जोड़ता है।',
      explanationEn: 'Correct! "and" connects two similar activities.',
    },
    {
      type: 'build',
      id: 'build-translate',
      quest: 1,
      promptHi: 'मैं अपने दोस्त के साथ पार्क में बास्केटबॉल खेलता हूँ।',
      answer: [
        'I',
        'play',
        'basketball',
        'in',
        'the',
        'park',
        'with',
        'my',
        'friend.',
      ],
      hint: {
        pattern: 'Subject + verb + activity + in + place + with + friend',
        example: 'I play basketball in the park with my friend.',
      },
    },
  ],
  speakFlow: [
    {
      id: 'speak-activity',
      quest: 2,
      promptEn: 'Tell me one activity you do with a friend.',
      promptHi: 'अपने दोस्त के साथ आप कौन सी activity करते हैं, बताइए।',
      hint: {
        pattern: 'I + verb + activity + with + my friend',
        example: 'I play chess with my friend.',
      },
    },
    {
      id: 'speak-and',
      quest: 2,
      promptEn: "Add another activity you do with the same friend, using 'and'.",
      promptHi: "एक और activity जोड़िए, 'and' का प्रयोग करके।",
      hint: {
        pattern: 'I + verb + activity + with + my friend, and + I + verb + activity',
        example: 'I play chess with my friend, and I study together.',
      },
    },
    {
      id: 'speak-but',
      quest: 2,
      promptEn: "Now say something you do with a friend that you don’t like, using 'but'.",
      promptHi: "ऐसी चीज़ बताइए जो आप अपने दोस्त के साथ करते हैं लेकिन आपको पसंद नहीं है, 'but' का प्रयोग करके।",
      hint: {
        pattern: 'I + verb + activity + with + my friend, but + I + verb + activity + ...',
        example: 'I go jogging with my friend, but I don’t enjoy it.',
      },
    },
    {
      id: 'speak-combine',
      quest: 2,
      promptEn: "Combine two activities you enjoy with your friend in one sentence using 'and' or 'but' as appropriate.",
      promptHi: 'दो पसंदीदा activities को एक sentence में जोड़िए, सही conjunction का उपयोग करके।',
      hint: {
        pattern: 'I + verb + activity + with + my friend, and/but + I + verb + activity',
        example: 'I play football with my friend, and we watch movies.',
      },
    },
    {
      id: 'speak-final',
      quest: 2,
      promptEn: 'Finally, tell me everything you usually do with your friend in a short paragraph.',
      promptHi: 'अंत में, अपने दोस्त के साथ आप आमतौर पर क्या करते हैं, एक छोटा paragraph में बताइए।',
      isFinal: true,
    },
  ],
};
