import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=6, day=2: learn + speaking.
export const week06Day02: DayLesson = {
  week: 6,
  day: 2,
  skillId: 'describe_home',
  weeklyOutcome: 'Describe your home and where things are.',
  dailyOutcome: 'Say where things are',
  learnFlow: [
    {
      type: 'intro',
      id: 'intro-1',
      quest: 1,
      emoji: '🏡',
      textHi: 'आज हम सीखेंगे कि घर में चीज़ें कहाँ हैं — यह English में कैसे कहें। चलिए शुरू करते हैं!',
      textEn: "Today we'll learn how to say where things are in your home in English. Let's start!",
    },
    {
      type: 'rule',
      id: 'rule-there',
      quest: 1,
      pattern: 'There is/are + [object] + [preposition] + [place].',
      example: 'There is a lamp on the table.',
      textHi: 'घर में चीज़ों की जगह बताने के लिए इस pattern का उपयोग करें।',
    },
    {
      type: 'rule',
      id: 'rule-prep',
      quest: 1,
      pattern: '[preposition] = in / on / under / next to',
      example: 'The book is on the shelf.',
      textHi: 'इन prepositions (in, on, under, next to) का प्रयोग करके स्थान बताइए।',
    },
    {
      type: 'mcq',
      id: 'mcq-1',
      quest: 1,
      promptHi: 'कौन सा वाक्य सही तरीके से बताता है कि बिस्तर कमरे में है?',
      promptEn: 'Which sentence correctly says the bed is in the room?',
      options: [
        {
          id: 'a',
          text: 'The bed is on my room.',
          correct: false,
        },
        {
          id: 'b',
          text: 'There is a bed in my room.',
          correct: true,
        },
        {
          id: 'c',
          text: 'There are a bed in my room.',
          correct: false,
        },
      ],
      explanationHi: 'सही! "There is a bed in my room." इस pattern को follow करता है।',
      explanationEn: 'Correct! "There is a bed in my room." follows the pattern.',
    },
    {
      type: 'build',
      id: 'build-1',
      quest: 1,
      promptHi: 'मेरे कमरे में एक बिस्तर है।',
      answer: [
        'There',
        'is',
        'a',
        'bed',
        'in',
        'my',
        'room.',
      ],
      hint: {
        pattern: 'There is + [object] + in + [place].',
        example: 'There is a bed in my room.',
      },
    },
    {
      type: 'build',
      id: 'build-2',
      quest: 1,
      promptHi: 'रसोई के बगल में एक फ्रिज है।',
      answer: [
        'There',
        'is',
        'a',
        'fridge',
        'next',
        'to',
        'the',
        'kitchen.',
      ],
      hint: {
        pattern: 'There is + [object] + next to + [place].',
        example: 'There is a fridge next to the kitchen.',
      },
    },
  ],
  speakFlow: [
    {
      id: 'speak-1',
      quest: 2,
      promptEn: 'Say where the bed is in your room.',
      promptHi: 'बताइए आपका बिस्तर आपके कमरे में कहाँ है।',
      hint: {
        pattern: 'There is + [object] + in + [place].',
        example: 'There is a bed in my room.',
      },
    },
    {
      id: 'speak-2',
      quest: 2,
      promptEn: 'Now say where the fridge is relative to the kitchen.',
      promptHi: 'अब बताइए आपका फ्रिज रसोई के बगल में कहाँ है।',
      hint: {
        pattern: 'There is + [object] + next to + [place].',
        example: 'There is a fridge next to the kitchen.',
      },
    },
    {
      id: 'speak-3',
      quest: 2,
      promptEn: 'Combine the two sentences into one short paragraph describing both items.',
      promptHi: 'दोनों वाक्यों को मिलाकर एक छोटा paragraph बनाइए जिसमें दोनों चीज़ों की जगह बताई गई हो।',
      hint: {
        pattern: 'There is + [object] + [preposition] + [place], and there is + [object] + [preposition] + [place].',
        example: 'There is a bed in my room, and there is a fridge next to the kitchen.',
      },
    },
    {
      id: 'speak-4',
      quest: 2,
      promptEn: 'Try again, a little faster, describing the same two items.',
      promptHi: 'फिर से बोलिए, थोड़ा तेज़, वही दो चीज़ें बताइए।',
      hint: {
        pattern: 'There is + [object] + [preposition] + [place]...',
        example: 'There is a bed in my room, and there is a fridge next to the kitchen.',
      },
    },
    {
      id: 'speak-5',
      quest: 2,
      promptEn: 'Last one — describe where a sofa, a lamp, and a TV are in your house.',
      promptHi: 'आखिरी सवाल — आपके घर में सोफ़ा, लैंप और टीवी कहाँ हैं, बताइए।',
      isFinal: true,
    },
  ],
};
