import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=7, day=6: review + speaking.
export const week07Day06: DayLesson = {
  week: 7,
  day: 6,
  skillId: 'describe_friend',
  weeklyOutcome: 'Talk about friends and what you do together.',
  dailyOutcome: 'Tell a short story about a friend',
  learnFlow: [
    {
      type: 'intro',
      id: 'intro-1',
      quest: 1,
      emoji: '👫',
      textHi: 'आज हम दोस्त के बारे में बात करेंगे — उनके बारे में बताना और साथ में क्या करते हैं।',
      textEn: 'Today we will talk about a friend — describing them and what you do together.',
    },
    {
      type: 'rule',
      id: 'rule-present',
      quest: 1,
      pattern: 'Subject + base verb (+ s/es for third person).',
      example: 'She plays cricket.',
      textHi: 'Present simple का उपयोग करके सामान्य कार्य बताइए।',
    },
    {
      type: 'rule',
      id: 'rule-and',
      quest: 1,
      pattern: 'Clause + and + clause.',
      example: 'I study English and I play football.',
      textHi: "'and' का प्रयोग दो कार्यों को जोड़ने के लिए करें।",
    },
    {
      type: 'mcq',
      id: 'mcq-and',
      quest: 1,
      promptHi: "कौन सा वाक्य सही तरीके से 'and' का उपयोग करता है?",
      promptEn: "Which sentence correctly uses 'and'?",
      options: [
        {
          id: 'a',
          text: 'I study English, I play football.',
          correct: false,
        },
        {
          id: 'b',
          text: 'I study English and I play football.',
          correct: true,
        },
        {
          id: 'c',
          text: 'I study English but I play football.',
          correct: false,
        },
      ],
      explanationHi: "सही! 'and' दो क्रियाओं को जोड़ता है।",
      explanationEn: "Correct! 'and' joins two actions.",
    },
    {
      type: 'mcq',
      id: 'mcq-but',
      quest: 1,
      promptHi: "'but' के साथ सही वाक्य चुनें।",
      promptEn: "Choose the correct sentence with 'but'.",
      options: [
        {
          id: 'a',
          text: 'She likes movies but she also likes reading.',
          correct: true,
        },
        {
          id: 'b',
          text: 'She likes movies and she also likes reading.',
          correct: false,
        },
        {
          id: 'c',
          text: 'She likes movies, also she likes reading.',
          correct: false,
        },
      ],
      explanationHi: "'but' विरोध दर्शाता है।",
      explanationEn: "'but' shows contrast.",
    },
    {
      type: 'build',
      id: 'build-translate',
      quest: 1,
      promptHi: 'मेरी दोस्त रीता हर रविवार को पार्क में मेरे साथ खेलती है।',
      answer: [
        'My',
        'friend',
        'Rita',
        'plays',
        'in',
        'the',
        'park',
        'with',
        'me',
        'every',
        'Sunday.',
      ],
      hint: {
        pattern: 'Subject + verb + ...',
        example: 'My friend Rita plays in the park with me every Sunday.',
      },
    },
  ],
  speakFlow: [
    {
      id: 'speak-describe',
      quest: 2,
      promptEn: 'Describe your friend in one sentence.',
      promptHi: 'अपनी दोस्त का एक वाक्य में वर्णन करें।',
      hint: {
        pattern: 'My friend + name + is + adjective.',
        example: 'My friend Anil is kind.',
      },
    },
    {
      id: 'speak-activities',
      quest: 2,
      promptEn: "Say what you usually do together using 'and'.",
      promptHi: "आप आम तौर पर साथ में क्या करते हैं, 'and' का उपयोग करके बताइए।",
      hint: {
        pattern: 'We + verb + and + we + verb.',
        example: 'We study English and we play cricket.',
      },
    },
    {
      id: 'speak-contrast',
      quest: 2,
      promptEn: "Now say something you do together but sometimes you do something different, using 'but'.",
      promptHi: "अब कुछ ऐसा कहिए जो आप साथ में करते हैं, लेकिन कभी‑कभी अलग भी करते हैं, 'but' का उपयोग करके।",
      hint: {
        pattern: 'We + verb + but + we + verb.',
        example: 'We go to the park, but sometimes we stay home.',
      },
    },
    {
      id: 'speak-story',
      quest: 2,
      promptEn: "Tell a short story about a day with your friend, using present simple, 'and', and 'but'.",
      promptHi: 'अपनी दोस्त के साथ एक दिन की छोटी कहानी बताइए, जिसमें present simple, and, लेकिन का प्रयोग हो।',
    },
    {
      id: 'speak-final',
      quest: 2,
      promptEn: 'One more time, tell the story clearly and confidently.',
      promptHi: 'एक बार फिर, कहानी स्पष्ट और आत्मविश्वास से बताइए।',
      isFinal: true,
    },
  ],
};
