import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=6, day=3: reading + speaking.
export const week06Day03: DayLesson = {
  week: 6,
  day: 3,
  skillId: 'describe_home',
  weeklyOutcome: 'Describe your home and where things are.',
  dailyOutcome: 'Describe one room',
  learnFlow: [
    {
      type: 'intro',
      id: 'read-intro',
      quest: 1,
      emoji: '📖',
      textHi: 'यह मेरा शयनकक्ष है। कमरे में एक बिस्तर, एक अलमारी, और एक डेस्क है। बिस्तर के बगल में एक लैंप है। लैंप डेस्क के ऊपर है।',
      textEn: 'This is my bedroom. The room has a bed, a wardrobe, and a desk. There is a lamp next to the bed. The lamp is on the desk.',
    },
    {
      type: 'rule',
      id: 'read-rule',
      quest: 1,
      pattern: 'There is/are + [noun] + [preposition] + [noun].',
      example: 'There is a lamp on the desk.',
      textHi: "'There is/are' वाक्य संरचना को समझिए।",
    },
    {
      type: 'mcq',
      id: 'read-loc-mcq',
      quest: 1,
      promptHi: 'पैरा में लैंप कहाँ है?',
      promptEn: 'Where is the lamp in the paragraph?',
      options: [
        {
          id: 'a',
          text: 'next to the bed',
          correct: true,
        },
        {
          id: 'b',
          text: 'under the bed',
          correct: false,
        },
        {
          id: 'c',
          text: 'in the wardrobe',
          correct: false,
        },
      ],
      explanationHi: 'सही! लैंप बिस्तर के बगल में है।',
      explanationEn: 'Correct! The lamp is next to the bed.',
    },
    {
      type: 'mcq',
      id: 'read-prep-mcq',
      quest: 1,
      promptHi: "'under' शब्द का मतलब क्या है?",
      promptEn: "What does the word 'under' mean?",
      options: [
        {
          id: 'a',
          text: 'ऊपर',
          correct: false,
        },
        {
          id: 'b',
          text: 'नीचे',
          correct: true,
        },
        {
          id: 'c',
          text: 'साथ',
          correct: false,
        },
      ],
      explanationHi: "'under' का मतलब नीचे होता है।",
      explanationEn: "'under' means below.",
    },
    {
      type: 'build',
      id: 'read-retell',
      quest: 1,
      promptHi: 'पैराग्राफ में कहा गया: लैंप डेस्क के ऊपर है — इसे अंग्रेज़ी में फिर से बनाइए।',
      answer: [
        'The',
        'lamp',
        'is',
        'on',
        'the',
        'desk.',
      ],
      hint: {
        pattern: '[A] is on the [B].',
        example: 'The book is on the table.',
      },
    },
  ],
  speakFlow: [
    {
      id: 'speak-name',
      quest: 2,
      promptEn: 'Say the name of your room.',
      promptHi: 'अपने कमरे का नाम बताइए।',
    },
    {
      id: 'speak-there-is',
      quest: 2,
      promptEn: 'Say one thing that is in your room.',
      promptHi: 'अपने कमरे में क्या है, एक चीज़ बताइए।',
      hint: {
        pattern: 'There is/are + [noun].',
        example: 'There is a window.',
      },
    },
    {
      id: 'speak-location',
      quest: 2,
      promptEn: 'Describe where an object is in your room using a preposition.',
      promptHi: 'अपने कमरे में एक वस्तु की स्थिति बताइए, जैसे "The book is under the table"।',
      hint: {
        pattern: '[A] is + preposition + the [B].',
        example: 'The phone is on the desk.',
      },
    },
    {
      id: 'speak-adj',
      quest: 2,
      promptEn: 'Describe your room with an adjective.',
      promptHi: 'अपने कमरे को एक adjective से describe कीजिए।',
      hint: {
        pattern: 'My [room] is + [adjective].',
        example: 'My bedroom is small.',
      },
    },
    {
      id: 'speak-final',
      quest: 2,
      promptEn: 'Now give a full description of your room, like the paragraph you just read.',
      promptHi: 'अब अपने कमरे का पूरा description दें, जैसा आप अभी पढ़े पैराग्राफ की तरह।',
      isFinal: true,
    },
  ],
};
