import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=7, day=7: practice + conversation + speaking + mission.
export const week07Day07: DayLesson = {
  week: 7,
  day: 7,
  skillId: 'describe_friend',
  weeklyOutcome: 'Talk about friends and what you do together.',
  dailyOutcome: 'Talk about a friend for 1–2 minutes',
  learnFlow: [
    {
      type: 'intro',
      id: 'practice-intro',
      quest: 1,
      emoji: '🔎',
      textHi: 'आज हम अपने दोस्त के बारे में बात करना अभ्यास करेंगे।',
      textEn: "Today we'll practice talking about a friend.",
    },
    {
      type: 'rule',
      id: 'present-simple-rule',
      quest: 1,
      pattern: 'Subject + base verb (+ object/complement)',
      example: 'She likes movies.',
      textHi: 'present simple का pattern: Subject + base verb + ...',
    },
    {
      type: 'mcq',
      id: 'mcq-verb-choice',
      quest: 1,
      promptHi: 'कौन सा वाक्य सही है?',
      promptEn: 'Which sentence is correct?',
      options: [
        {
          id: 'a',
          text: 'He play cricket on weekends.',
          correct: false,
        },
        {
          id: 'b',
          text: 'He plays cricket on weekends.',
          correct: true,
        },
        {
          id: 'c',
          text: 'He playing cricket on weekends.',
          correct: false,
        },
      ],
      explanationHi: 'सही! He plays ... present simple में -s जोड़ते हैं।',
      explanationEn: 'Correct! In present simple, third‑person singular adds –s.',
    },
    {
      type: 'build',
      id: 'build-translate-friend',
      quest: 1,
      promptHi: 'मेरी दोस्त सिमरन हर रविवार को पार्क में चलना पसंद करती है।',
      answer: [
        'My',
        'friend',
        'Simran',
        'likes',
        'to',
        'walk',
        'in',
        'the',
        'park',
        'on',
        'Sundays.',
      ],
      hint: {
        pattern: 'Subject + likes + to + verb + ...',
        example: 'My friend Simran likes to walk in the park on Sundays.',
      },
    },
    {
      type: 'build',
      id: 'build-and-but',
      quest: 1,
      promptHi: 'वो पढ़ना पसंद करती है, लेकिन वह अक्सर देर से सोती है।',
      answer: [
        'She',
        'likes',
        'reading',
        'but',
        'she',
        'often',
        'sleeps',
        'late.',
      ],
      hint: {
        pattern: '[Clause 1], but [Clause 2].',
        example: 'She likes reading, but she often sleeps late.',
      },
    },
  ],
  speakFlow: [
    {
      id: 'conv-greet',
      quest: 2,
      promptEn: 'Nova asks about your friend. Respond with name, where they are from, and one activity they like.',
      promptHi: 'Nova पूछती है, “आपकी दोस्त कौन है और उसे क्या करना पसंद है?” जवाब दें।',
      hint: {
        pattern: 'My friend + name + is from + place + and + likes + ...',
        example: 'My friend Simran is from Delhi and likes playing cricket.',
      },
    },
    {
      id: 'conv-followup',
      quest: 2,
      promptEn: 'Nova asks a follow‑up about something your friend doesn’t like. Answer naturally using “but”.',
      promptHi: 'Nova पूछती है, “आपकी दोस्त क्या नहीं पसंद करती?” जवाब दें और “but” का उपयोग करें।',
      hint: {
        pattern: 'She likes ... but she doesn’t like ...',
        example: 'She likes movies but she doesn’t like horror films.',
      },
    },
    {
      id: 'speak-guided',
      quest: 3,
      promptEn: 'Describe your friend in 2–3 sentences, using present simple and ‘and’ to add details.',
      promptHi: 'अपने दोस्त के बारे में 2‑3 वाक्य बताइए, present simple और ‘and’ का प्रयोग करके।',
      hint: {
        pattern: '[Sentence 1] and [Sentence 2].',
        example: 'My friend Arjun is from Mumbai and he enjoys playing football.',
      },
    },
    {
      id: 'speak-free',
      quest: 3,
      promptEn: 'Now speak for 1 minute about your friend, adding at least one ‘but’ contrast.',
      promptHi: 'अब 1 मिनट तक अपने दोस्त के बारे में बात कीजिए, कम से कम एक ‘but’ वाक्य जोड़िए।',
    },
    {
      id: 'weekly-mission',
      quest: 4,
      promptEn: 'Talk for 1–2 minutes about a friend: name, where they are from, what you do together, and something you both enjoy, using present simple, ‘and’, ‘but’.',
      promptHi: '1‑2 मिनट में अपने दोस्त के बारे में बात कीजिए: नाम, कहाँ से है, आप साथ क्या करते हैं, और एक चीज़ जो आप दोनों को पसंद है, present simple, ‘and’, ‘but’ का उपयोग करके।',
      isFinal: true,
      missionLabel: 'WEEKLY MISSION',
    },
  ],
};
