import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=6, day=1: learn + translation + speaking.
export const week06Day01: DayLesson = {
  week: 6,
  day: 1,
  skillId: 'describe_home',
  weeklyOutcome: 'Describe your home and where things are.',
  dailyOutcome: 'Name rooms and common objects',
  learnFlow: [
    {
      type: 'intro',
      id: 'intro-1',
      quest: 1,
      emoji: '🏠',
      textHi: 'आज हम सीखेंगे कि घर में चीज़ें कहाँ हैं, "there is/are" और स्थान संबंधी शब्दों का उपयोग कैसे करें।',
      textEn: 'Today we will learn how to use "there is/are" and prepositions to talk about where things are in a house.',
    },
    {
      type: 'rule',
      id: 'rule-1',
      quest: 1,
      pattern: 'There is + [object] + [preposition] + [place].',
      example: 'There is a sofa in the living room.',
      textHi: 'एक वस्तु का स्थान बताने के लिए यह pattern उपयोग करें।',
    },
    {
      type: 'rule',
      id: 'rule-2',
      quest: 1,
      pattern: 'There are + [objects] + [preposition] + [place].',
      example: 'There are three books on the table.',
      textHi: 'बहु-वचन वस्तुओं के लिए यह pattern।',
    },
    {
      type: 'mcq',
      id: 'mcq-1',
      quest: 1,
      promptHi: 'इनमें से कौन सा वाक्य "there is" का सही उपयोग दिखाता है?',
      promptEn: 'Which sentence correctly uses "there is"?',
      options: [
        {
          id: 'a',
          text: 'There are a lamp in the bedroom.',
          correct: false,
        },
        {
          id: 'b',
          text: 'There is a lamp in the bedroom.',
          correct: true,
        },
        {
          id: 'c',
          text: 'There is lamps in the bedroom.',
          correct: false,
        },
      ],
      explanationHi: 'सही! "There is a lamp in the bedroom." एकवचन वस्तु के लिए सही है।',
      explanationEn: 'Correct! "There is a lamp in the bedroom." is the proper singular form.',
    },
    {
      type: 'build',
      id: 'build-1',
      quest: 1,
      promptHi: 'मेरे कमरे में एक बिस्तर है।',
      answer: [
        'There',
        'is',
        'a',
        'bed',
        'in',
        'my',
        'room.',
      ],
      hint: {
        pattern: 'There is + [object] + in + [place]',
        example: 'There is a bed in my room.',
      },
    },
    {
      type: 'intro',
      id: 'intro-2',
      quest: 2,
      emoji: '🔁',
      textHi: 'अब हम इन हिंदी वाक्यों को English में translate करेंगे, ताकि आप घर के विभिन्न कमरों और वस्तुओं को describe कर सकें।',
      textEn: 'Now we will translate these Hindi sentences into English so you can describe rooms and objects in a house.',
    },
    {
      type: 'rule',
      id: 'rule-3',
      quest: 2,
      pattern: 'The + [room] + has + [object].',
      example: 'The kitchen has a fridge.',
      textHi: 'कमरे में मौजूद वस्तु बताने के लिए यह pattern प्रयोग करें।',
    },
    {
      type: 'mcq',
      id: 'mcq-2',
      quest: 2,
      promptHi: 'निम्नलिखित में से कौन सा वाक्य "The kitchen has a fridge." का सही translation है?',
      promptEn: 'Which sentence is the correct translation of "The kitchen has a fridge."?',
      options: [
        {
          id: 'a',
          text: 'Kitchen the has fridge a.',
          correct: false,
        },
        {
          id: 'b',
          text: 'The kitchen has a fridge.',
          correct: true,
        },
        {
          id: 'c',
          text: 'A fridge has the kitchen.',
          correct: false,
        },
      ],
      explanationHi: 'सही! "The kitchen has a fridge." सही क्रम है।',
      explanationEn: 'Correct! "The kitchen has a fridge." is the proper word order.',
    },
    {
      type: 'build',
      id: 'build-2',
      quest: 2,
      promptHi: 'रसोई में एक फ्रिज है।',
      answer: [
        'The',
        'kitchen',
        'has',
        'a',
        'fridge.',
      ],
      hint: {
        pattern: 'The + [room] + has + a + [object]',
        example: 'The kitchen has a fridge.',
      },
    },
    {
      type: 'build',
      id: 'build-3',
      quest: 2,
      promptHi: 'बेडरूम में दो बिस्तर हैं।',
      answer: [
        'There',
        'are',
        'two',
        'beds',
        'in',
        'the',
        'bedroom.',
      ],
      hint: {
        pattern: 'There are + [number] + [plural noun] + in + the + [room]',
        example: 'There are two beds in the bedroom.',
      },
    },
  ],
  speakFlow: [
    {
      id: 'speak-1',
      quest: 3,
      promptEn: 'Name three rooms in your house.',
      promptHi: 'अपने घर के तीन कमरों के नाम बताइए।',
      hint: {
        pattern: 'The + [room]',
        example: 'The kitchen',
      },
    },
    {
      id: 'speak-2',
      quest: 3,
      promptEn: 'Describe where the sofa is in your living room.',
      promptHi: 'अपने लिविंग रूम में सोफ़ा कहाँ है, बताइए।',
      hint: {
        pattern: 'There is a sofa in the living room.',
        example: 'There is a sofa in the living room.',
      },
    },
    {
      id: 'speak-3',
      quest: 3,
      promptEn: 'Say what is on the table in your bedroom.',
      promptHi: 'आपके बेडरूम में टेबल पर क्या है, बताइए।',
      hint: {
        pattern: 'There is a lamp on the table.',
        example: 'There is a lamp on the table.',
      },
    },
    {
      id: 'speak-4',
      quest: 3,
      promptEn: 'Use "next to" to describe something in your kitchen.',
      promptHi: 'रसोई में बर्तन अलमारी के बगल में हैं, इसे अंग्रेज़ी में कहिए।',
      hint: {
        pattern: 'The pots are next to the cupboard.',
        example: 'The pots are next to the cupboard.',
      },
    },
    {
      id: 'speak-5',
      quest: 3,
      promptEn: 'Give a short paragraph describing two rooms and where two objects are located.',
      promptHi: 'दो कमरों और उनमें दो वस्तुओं के स्थान के बारे में एक छोटा paragraph बनाइए।',
      isFinal: true,
    },
  ],
};
