import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=5, day=1: learn + translation + speaking.
export const week05Day01: DayLesson = {
  week: 5,
  day: 1,
  skillId: 'describe_family',
  weeklyOutcome: 'Describe family members and relationships.',
  dailyOutcome: 'Name family members and relationships',
  learnFlow: [
    {
      type: 'intro',
      id: 'intro-1',
      quest: 1,
      emoji: '👪',
      textHi: 'आज हम सीखेंगे कि परिवार के सदस्य को English में कैसे बताएं — have/has और possessive का उपयोग।',
      textEn: 'Today we will learn how to talk about family members in English using have/has and possessives.',
    },
    {
      type: 'rule',
      id: 'rule-have',
      quest: 1,
      pattern: 'I have + [family member].',
      example: 'I have a brother.',
      textHi: "जब आप अपने परिवार के सदस्य के बारे में बात करना चाहते हैं, तो 'have' का प्रयोग करें।",
    },
    {
      type: 'rule',
      id: 'rule-has',
      quest: 1,
      pattern: 'He/She has + [family member].',
      example: 'She has a sister.',
      textHi: "तीसरे व्यक्ति के लिए 'has' इस्तेमाल होता है।",
    },
    {
      type: 'mcq',
      id: 'mcq-have',
      quest: 1,
      promptHi: 'निम्न में से कौन सा वाक्य सही है जब आप अपने पिता के बारे में बात कर रहे हैं?',
      promptEn: 'Which sentence correctly talks about your father?',
      options: [
        {
          id: 'a',
          text: 'I has a father.',
          correct: false,
        },
        {
          id: 'b',
          text: 'I have a father.',
          correct: true,
        },
        {
          id: 'c',
          text: 'I have father.',
          correct: false,
        },
      ],
      explanationHi: 'सही! "I have a father." सही संरचना है।',
      explanationEn: 'Correct! "I have a father." is the proper structure.',
    },
    {
      type: 'build',
      id: 'build-translate1',
      quest: 1,
      promptHi: 'मेरे पास एक बड़ी माँ है।',
      answer: [
        'I',
        'have',
        'a',
        'big',
        'mother',
      ],
      hint: {
        pattern: 'I have + [article] + [adjective] + [noun]',
        example: 'I have a tall brother.',
      },
    },
    {
      type: 'intro',
      id: 'intro-2',
      quest: 2,
      emoji: '🧩',
      textHi: 'अब हम परिवार के सदस्य के साथ possessive adjectives का उपयोग करके वाक्य बनाते हैं।',
      textEn: 'Now we will form sentences using possessive adjectives with family members.',
    },
    {
      type: 'rule',
      id: 'rule-poss',
      quest: 2,
      pattern: '[Possessive adjective] + [family member] + verb',
      example: 'My sister is a teacher.',
      textHi: 'Possessive adjectives जैसे My, Your, His, Her आदि का प्रयोग करें।',
    },
    {
      type: 'mcq',
      id: 'mcq-poss',
      quest: 2,
      promptHi: 'आपकी बहन के बारे में बताने का सही वाक्य कौन सा है?',
      promptEn: 'Which sentence correctly describes your sister?',
      options: [
        {
          id: 'a',
          text: 'Your sister is a doctor.',
          correct: true,
        },
        {
          id: 'b',
          text: 'My sister are a doctor.',
          correct: false,
        },
        {
          id: 'c',
          text: 'My sister is doctor.',
          correct: false,
        },
      ],
      explanationHi: 'सही! "Your sister is a doctor." सही संरचना है।',
      explanationEn: 'Correct! "Your sister is a doctor." uses the right structure.',
    },
    {
      type: 'build',
      id: 'build-translate2',
      quest: 2,
      promptHi: 'उसका पिता एक डॉक्टर है।',
      answer: [
        'His',
        'father',
        'is',
        'a',
        'doctor',
      ],
      hint: {
        pattern: 'His + [noun] + is + a + [profession]',
        example: 'His father is a doctor.',
      },
    },
    {
      type: 'build',
      id: 'build-translate3',
      quest: 2,
      promptHi: 'हमारी बड़ी बेटी पढ़ाई करती है।',
      answer: [
        'Our',
        'elder',
        'daughter',
        'studies',
      ],
      hint: {
        pattern: 'Our + [adjective] + [noun] + verb',
        example: 'Our elder daughter studies.',
      },
    },
  ],
  speakFlow: [
    {
      id: 'speak-1',
      quest: 3,
      promptEn: "Say a sentence about a family member you have, using 'have'.",
      promptHi: "अपने किसी परिवार के सदस्य के बारे में 'have' का उपयोग करके एक वाक्य बोलिए।",
      hint: {
        pattern: 'I have + [family member]',
        example: 'I have a sister.',
      },
    },
    {
      id: 'speak-2',
      quest: 3,
      promptEn: "Talk about a family member of someone else using 'has'.",
      promptHi: "किसी और के परिवार के सदस्य के बारे में 'has' का उपयोग करके एक वाक्य बोलिए।",
      hint: {
        pattern: 'He/She has + [family member]',
        example: 'She has a brother.',
      },
    },
    {
      id: 'speak-3',
      quest: 3,
      promptEn: 'Describe your sister using a possessive adjective.',
      promptHi: 'अपने बहन का वर्णन possessive adjective से करें।',
      hint: {
        pattern: 'My sister + verb',
        example: 'My sister studies.',
      },
    },
    {
      id: 'speak-4',
      quest: 3,
      promptEn: 'Give a short introduction of two family members, including relationships.',
      promptHi: 'दो परिवार के सदस्य का परिचय दें, उनके रिश्ते सहित।',
      hint: {
        pattern: 'This is my + [relationship] + ...',
        example: 'This is my brother, he works as an engineer.',
      },
    },
    {
      id: 'speak-5',
      quest: 3,
      promptEn: 'Combine everything: talk about who you have, who they have, and use possessives to describe them.',
      promptHi: 'सब कुछ मिलाकर बोलिए: आपके पास कौन है, उनके पास कौन है, और possessives से उनका वर्णन करें।',
      hint: {
        pattern: 'I have ... He/she has ... My ... is ...',
        example: 'I have a sister. She has a son. My sister is a teacher.',
      },
      isFinal: true,
    },
  ],
};
