import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=5, day=4: conversation.
export const week05Day04: DayLesson = {
  week: 5,
  day: 4,
  skillId: 'describe_family',
  weeklyOutcome: 'Describe family members and relationships.',
  dailyOutcome: 'Ask someone about their family',
  learnFlow: [],
  speakFlow: [
    {
      id: 'converse-intro-family',
      quest: 1,
      promptEn: 'Nova says: I have a mother, a father, and a sister. Ask her about her family.',
      promptHi: 'Nova कहती है: मेरे पास माँ, पिता और बहन है। उनसे उनके परिवार के बारे में पूछिए।',
      hint: {
        pattern: 'Do you have...?',
        example: 'Do you have any brothers or sisters?',
      },
    },
    {
      id: 'converse-ask-members',
      quest: 1,
      promptEn: 'Ask Nova how many brothers and sisters she has.',
      promptHi: 'Nova से पूछिए कि उसके कितने भाई‑बहन हैं।',
      hint: {
        pattern: 'How many brothers/sisters do you have?',
        example: 'How many sisters do you have?',
      },
    },
    {
      id: 'converse-describe',
      quest: 1,
      promptEn: "Nova says she has one brother and two sisters. Describe one of them using 'has' and a simple adjective.",
      promptHi: "Nova बताती है कि उसके एक भाई और दो बहनें हैं। उनमें से एक को 'has' और एक सरल विशेषण से वर्णन कीजिए।",
      hint: {
        pattern: 'My brother has + [adjective] + [noun].',
        example: 'My brother has short hair.',
      },
    },
    {
      id: 'converse-follow-up',
      quest: 1,
      promptEn: "Ask Nova about her parents' occupations using possessive forms.",
      promptHi: 'Nova से उसके माता‑पिता के पेशे के बारे में पूछिए, possessive रूप प्रयोग करके।',
      hint: {
        pattern: 'What does your mother/father do?',
        example: 'What does your mother do?',
      },
    },
    {
      id: 'converse-wrap',
      quest: 1,
      promptEn: 'Thank Nova and summarize what you learned about her family.',
      promptHi: 'Nova को धन्यवाद दीजिए और उसके परिवार के बारे में जो सीखा, उसका सारांश कहिए।',
      isFinal: true,
    },
  ],
};
