import type { DayLesson } from '@/lib/curriculum/lesson-types';

// Generated by scripts/content-gen/generate_days.ts (Groq openai/gpt-oss-120b), validated against
// content/curriculum/everyday-confidence/beginner/days.json + skills.json before being written.
// week=5, day=7: practice + conversation + speaking + mission.
export const week05Day07: DayLesson = {
  week: 5,
  day: 7,
  skillId: 'describe_family',
  weeklyOutcome: 'Describe family members and relationships.',
  dailyOutcome: 'Describe your family for 1–2 minutes',
  learnFlow: [
    {
      type: 'intro',
      id: 'family-warmup',
      quest: 1,
      emoji: '👪',
      textHi: 'आइए अपने परिवार के बारे में बात करने की तैयारी करें।',
      textEn: "Let's get ready to talk about your family.",
    },
    {
      type: 'mcq',
      id: 'have-has-choice',
      quest: 1,
      promptHi: 'इनमें से कौन‑सा वाक्य सही है?',
      promptEn: 'Which sentence is correct?',
      options: [
        {
          id: 'a',
          text: 'She have two brothers.',
          correct: false,
        },
        {
          id: 'b',
          text: 'She has two brothers.',
          correct: true,
        },
        {
          id: 'c',
          text: 'She has two brother.',
          correct: false,
        },
      ],
      explanationHi: '"She has" सही है क्योंकि वह तृतीय पुरुष एकवचन है।',
      explanationEn: '"She has" is correct because the subject is third‑person singular.',
    },
    {
      type: 'mcq',
      id: 'possessive-pronoun',
      quest: 1,
      promptHi: '"My" का सही हिंदी अनुवाद कौन‑सा है?',
      promptEn: 'Which Hindi translation matches "my"?',
      options: [
        {
          id: 'a',
          text: 'उसका',
          correct: false,
        },
        {
          id: 'b',
          text: 'मेरे',
          correct: true,
        },
        {
          id: 'c',
          text: 'उनकी',
          correct: false,
        },
      ],
      explanationHi: '"मेरे" का अर्थ "my" होता है।',
      explanationEn: '"मेरे" means "my".',
    },
    {
      type: 'build',
      id: 'combine-facts',
      quest: 1,
      promptHi: 'मेरी माँ डॉक्टर है और मेरे पिता इंजीनियर हैं।',
      answer: [
        'My',
        'mother',
        'is',
        'a',
        'doctor',
        'and',
        'my',
        'father',
        'is',
        'an',
        'engineer.',
      ],
      hint: {
        pattern: '[Subject] is a [profession] and [subject] is a [profession].',
        example: 'My mother is a doctor and my father is an engineer.',
      },
    },
    {
      type: 'build',
      id: 'translate-hindi',
      quest: 1,
      promptHi: 'मेरे दो बड़े भाई हैं और मेरी एक छोटी बहन है।',
      answer: [
        'I',
        'have',
        'two',
        'older',
        'brothers',
        'and',
        'I',
        'have',
        'one',
        'younger',
        'sister.',
      ],
      hint: {
        pattern: 'I have + [number] + [relationship] + and + I have + [number] + [relationship].',
        example: 'I have two older brothers and I have one younger sister.',
      },
    },
  ],
  speakFlow: [
    {
      id: 'convo-greet',
      quest: 2,
      promptEn: 'Nova says: "Tell me about the people you live with." Respond in English.',
      promptHi: 'Nova कहती है: "आपके साथ कौन‑कौन रहता है?" अंग्रेज़ी में जवाब दीजिए।',
      hint: {
        pattern: 'I live with + [family members].',
        example: 'I live with my parents and my sister.',
      },
    },
    {
      id: 'convo-detail',
      quest: 2,
      promptEn: 'Nova asks: "What does your brother do?" Answer naturally.',
      promptHi: 'Nova पूछती है: "आपके भाई क्या करते हैं?" स्वाभाविक रूप से जवाब दीजिए।',
      hint: {
        pattern: 'My brother + [verb] + [occupation].',
        example: 'My brother works as a teacher.',
      },
    },
    {
      id: 'convo-repair',
      quest: 2,
      promptEn: "Nova says she didn't understand the age of your sister. Clarify.",
      promptHi: 'Nova को आपकी बहन की उम्र समझ नहीं आई। स्पष्ट कीजिए।',
      hint: {
        pattern: 'My sister is + [age] + years old.',
        example: 'My sister is twelve years old.',
      },
    },
    {
      id: 'convo-unexpected',
      quest: 2,
      promptEn: 'Nova asks an unexpected question: "Do you celebrate any family festivals together?" Reply.',
      promptHi: 'Nova एक अनपेक्षित सवाल पूछती है: "क्या आप सभी साथ में कोई पारिवारिक त्यौहार मनाते हैं?" जवाब दीजिए।',
      hint: {
        pattern: 'Yes, we + [verb] + [festival] + together.',
        example: 'Yes, we celebrate Diwali together.',
      },
    },
    {
      id: 'convo-feedback',
      quest: 2,
      promptEn: 'Nova gives feedback: try to use "have/has" correctly when talking about family members.',
      promptHi: 'Nova फीडबैक देती है: परिवार के बारे में बात करते समय "have/has" सही ढंग से इस्तेमाल करें। फिर से जवाब दीजिए।',
      hint: {
        pattern: 'I have + [family member], He/She has + [family member].',
        example: 'I have a brother. She has a cousin.',
      },
    },
    {
      id: 'speak-guided',
      quest: 3,
      promptEn: 'Describe your immediate family in two sentences, using "have/has" and possessives.',
      promptHi: 'अपने निकटतम परिवार का वर्णन दो वाक्यों में करें, "have/has" और possessive का उपयोग करें।',
      hint: {
        pattern: 'I have + [family members]. My + [relation] + is + [detail].',
        example: 'I have a mother and a father. My mother is a teacher.',
      },
    },
    {
      id: 'speak-semi',
      quest: 3,
      promptEn: 'Add details about ages and one hobby each family member likes.',
      promptHi: 'प्रत्येक सदस्य की उम्र और एक शौक जोड़ें।',
      hint: {
        pattern: 'My + [relation] + is + [age] + years old and likes + [hobby].',
        example: 'My brother is 20 years old and likes cricket.',
      },
    },
    {
      id: 'speak-free',
      quest: 3,
      promptEn: 'Speak for about one minute describing your family without stopping.',
      promptHi: 'लगभग एक मिनट तक अपने परिवार के बारे में बिना रुके बोलिए।',
      hint: {
        pattern: 'Start with "I have...", then add details, keep a natural rhythm.',
        example: 'I have two sisters and one brother...',
      },
    },
    {
      id: 'speak-feedback',
      quest: 3,
      promptEn: 'Nova gives feedback on fluency. Try again, focusing on smoother transitions.',
      promptHi: 'Nova प्रवाह पर फीडबैक देती है। फिर से बोलिए, संक्रमण को आसान बनाइए।',
      hint: {
        pattern: 'Use connectors like "and", "also", "plus".',
        example: 'I have a sister, and she loves painting.',
      },
    },
    {
      id: 'weekly-mission',
      quest: 4,
      promptEn: 'Give a 1–2 minute description of your family: names, ages, relationships, what they do, and one thing each likes. Imagine you are introducing them to a new friend.',
      promptHi: 'अपना परिवार 1–2 मिनट में बताइए: नाम, उम्र, रिश्ते, वे क्या करते हैं, और प्रत्येक की एक पसंद। मानिए आप उन्हें एक नए दोस्त से मिलवा रहे हैं।',
      isFinal: true,
      missionLabel: 'WEEKLY MISSION',
    },
  ],
};
